---
- name: Check if Zscaler repo is already installed.
  stat:
    path: "{{ zscaler_repofile_path }}"
  register: zscaler_repofile_stat

- name: Import zscaler GPG Key
  rpm_key:
    key: "{{ zpaconnector_repo_gpg_key_url }}"
    state: present
  when: not zscaler_repofile_stat.stat.exists

- name: Copy Zscaler repo to repos.d
  ansible.builtin.copy:
    src: etc_yumreposd_zscaler.repo
    dest: "{{ zscaler_repofile_path }}"
    owner: root
    group: root
    mode: '0644'
  when: not zscaler_repofile_stat.stat.exists

# - name: Install ZPA Connector
#   yum:
#     name: "zpa-connector"
#     state: present
#   when: not zscaler_connector_stat.stat.exists

# - name: ZPA Start and Enable
#   service:
#     name: zpa-connector
#     state: started
#     enabled: yes